version: '3.8'

services:
  app:
    build: .
    ports:
      - "10000:10000"
    environment:
      - NODE_ENV=development
      - PORT=10000
      - MONGODB_URI=mongodb://mongodb:27017/lindas-nut-butter
      - JWT_SECRET=dev_jwt_secret
      - ADMIN_JWT_SECRET=dev_admin_jwt_secret
      - CUSTOMER_JWT_SECRET=dev_customer_jwt_secret
      - REFRESH_TOKEN_SECRET=dev_refresh_secret
      - ADMIN_REFRESH_TOKEN_SECRET=dev_admin_refresh_secret
      - PUBLIC_URL=http://localhost:10000
    depends_on:
      - mongodb
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/server/node_modules

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=lindas-nut-butter

volumes:
  mongodb_data:
